# This rule is not used by the project twinscale-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.core.twinscale.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: twinscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: core-mqtttrigger-editor-role
rules:
- apiGroups:
  - core.core.twinscale.io
  resources:
  - mqtttriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.core.twinscale.io
  resources:
  - mqtttriggers/status
  verbs:
  - get
