apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external
  namespace: twinscale
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30072       # your chosen AMQP NodePort
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883       # your existing MQTT NodePort
