apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: twinscale
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: mqtt-dispatcher
        static_configs:
          - targets: ["mqtt-dispatcher:8080"]
      - job_name: cloud-event-dispatcher
        static_configs:
          - targets: ["cloud-event-dispatcher:8081"]
      - job_name: redis
        static_configs:
          - targets: ["redis-metrics.twinscale.svc.cluster.local:9121"]
