architecture: replication
auth:
  enabled: true
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
nodeSelector:
  ktwin-node: "core"
master:
  kind: StatefulSet
  persistence:
    enabled: true
    size: 8Gi
replica:
  replicaCount: 2
  kind: StatefulSet
  persistence:
    enabled: true
    size: 8Gi
metrics:
  enabled: true
  service:
    enabled: true
