apiVersion: core.core.twinscale.io/v0
kind: EventStore
metadata:
  labels:
    app.kubernetes.io/name: twinscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventstore-sample
spec:
  # TODO(user): Add fields here
