apiVersion: core.core.twinscale.io/v0
kind: MQTTTrigger
metadata:
  name: mqtttrigger
  namespace: twinscale
  labels:
    app.kubernetes.io/name: twinscale-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  # TODO(user): Add fields here
