apiVersion: core.core.twinscale.io/v0
kind: Visualisation
metadata:
  name: visualisation
  namespace: twinscale
spec:
  # ── timeout is optional (defaults to “0” in code) ──

  dispatcherResources:        # required so that .Requests.Cpu/Memory and .Limits.Cpu/Memory are non-nil
    requests:
      cpu:    "50m"
      memory: "64Mi"
    limits:
      cpu:    "100m"
      memory: "128Mi"
