apiVersion: dtd.core.twinscale.io/v0
kind: TwinInterface
metadata:
  name: twininterface
  namespace: twinscale
spec:
  service:
    template:
      metadata: {}    # prevents nil-pointer panics
      spec:
        # Providing spec.service with at least one container forces the controller to:
        #   • Create a Knative Service named "twininterface"
        #   • Create a Trigger called "twininterface"
        #   • Create an MQTT dispatcher binding, etc.
        containers:
          - name: twin-container
            image: gcr.io/google-samples/hello-app:1.0
